# Generated by Django 3.2.4 on 2021-07-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RTSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='screenshot_dir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rtsp.project')),
                ('rtsp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rtsp.rtsp')),
                ('screenshot_dir', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='rtsp.screenshot_dir')),
            ],
        ),
    ]
