# Generated by Django 3.2.11 on 2022-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp', '0002_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='screenshot_dir',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='screenshot_dir',
        ),
    ]
